version: '3'

vars:
  GIT_COMMIT:
    sh: git log -n 1 --format=%h

  GO_PACKAGES:
    sh: go list ./...

env:
  CGO_ENABLED: '0'

tasks:

  default:
    cmds:
      - task: test

  install:
    desc: Installs Task
    cmds:
      - go install -v -ldflags="-w -s -X main.version={{.GIT_COMMIT}}" ./cmd/smart-git

  cli-deps:
    desc: Downloads CLI dependencies
    cmds:
      - task: go-get
        vars: { REPO: golang.org/x/lint/golint }
      - task: go-get
        vars: { REPO: github.com/goreleaser/goreleaser }
      - task: go-get
        vars: { REPO: github.com/goreleaser/godownloader }

  clean:
    desc: Cleans temp files and folders
    cmds:
      - rm -rf dist/

  lint:
    desc: Runs golint
    cmds:
      - golint {{catLines .GO_PACKAGES}}
    silent: true

  test:
    desc: Runs test suite
    deps: [ install ]
    cmds:
      - go test {{catLines .GO_PACKAGES}}

  test-release:
    desc: Tests release process without publishing
    cmds:
      - goreleaser --snapshot --rm-dist

  gen-install-script:
    desc: Generate install script using https://github.com/goreleaser/godownloader
    cmds:
      - godownloader --repo immanoj16/smart-git -o install-smart-git.sh
      - cp ./install-smart-git.sh ./docs/install.sh

  ci:
    - task: go-get
      vars: { REPO: golang.org/x/lint/golint }
    - task: lint
    - task: test

  go-get: go get -u {{.REPO}}

  packages:
    cmds:
      - echo '{{.GO_PACKAGES}}'
    silent: true
